sudo: false
language: node_js
node_js:
  - "8.1.0"

cache:
  directories:
    - node_modules

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: hartbeatnt/homepage
  bucket: natehart.xyz
  region: us-west-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: natehart.xyz
  key: latest.zip
  bundle_type: zip
  application: homepgae
  deployment_group: BlueGreenDemoFleet-a94q68z
  region: serverRegionHERE
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip